-- Insert guides into guides_temp table
-- This migration adds 14 guides with their complete information

-- Guide 1: Karel Gelin
INSERT INTO public.guides_temp (
  id, name, cities, languages, tour_types, preferences, availability, tours_done, 
  content, phonenumber, google_calendar_id, Email, is_favourite, profile_picture, 
  birthday, photos_taken_frequency, photos_taken_amount, requested_client_info
) VALUES (
  1,
  'Karel Gelin',
  ARRAY['Leuven']::text[],
  ARRAY['Nederlands', 'Engels', 'Frans']::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  'No calendar connected',
  2,
  'Adres: Pieter Coutereelstraat 4, 3000 Leuven',
  '+32473346935',
  NULL,
  'nomulpe@gmail.com',
  NULL,
  'https://rwrfobawfbfsggczofao.supabase.co/storage/v1/object/public/WebshopItemsImages/Guide%20Photos/1/guide_1_1767103848891.png',
  '1999-09-01'::date,
  4,
  22,
  0
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cities = EXCLUDED.cities,
  languages = EXCLUDED.languages,
  tour_types = EXCLUDED.tour_types,
  preferences = EXCLUDED.preferences,
  availability = EXCLUDED.availability,
  tours_done = EXCLUDED.tours_done,
  content = EXCLUDED.content,
  phonenumber = EXCLUDED.phonenumber,
  google_calendar_id = EXCLUDED.google_calendar_id,
  Email = EXCLUDED.Email,
  is_favourite = EXCLUDED.is_favourite,
  profile_picture = EXCLUDED.profile_picture,
  birthday = EXCLUDED.birthday,
  photos_taken_frequency = EXCLUDED.photos_taken_frequency,
  photos_taken_amount = EXCLUDED.photos_taken_amount,
  requested_client_info = EXCLUDED.requested_client_info;

-- Guide 2: Marc Debrabandere
INSERT INTO public.guides_temp (
  id, name, cities, languages, tour_types, preferences, availability, tours_done, 
  content, phonenumber, google_calendar_id, Email, is_favourite, profile_picture, 
  birthday, photos_taken_frequency, photos_taken_amount, requested_client_info
) VALUES (
  2,
  'Marc Debrabandere',
  ARRAY['Brussel', 'Brugge']::text[],
  ARRAY['Nederlands', 'Engels', 'Frans']::text[],
  ARRAY[]::text[],
  '{}'::jsonb,
  'No calendar connected',
  5,
  NULL,
  '+32473346935',
  NULL,
  'nomulpe@gmail.com',
  NULL,
  NULL,
  NULL,
  2,
  12,
  1
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cities = EXCLUDED.cities,
  languages = EXCLUDED.languages,
  tour_types = EXCLUDED.tour_types,
  preferences = EXCLUDED.preferences,
  availability = EXCLUDED.availability,
  tours_done = EXCLUDED.tours_done,
  content = EXCLUDED.content,
  phonenumber = EXCLUDED.phonenumber,
  google_calendar_id = EXCLUDED.google_calendar_id,
  Email = EXCLUDED.Email,
  is_favourite = EXCLUDED.is_favourite,
  profile_picture = EXCLUDED.profile_picture,
  birthday = EXCLUDED.birthday,
  photos_taken_frequency = EXCLUDED.photos_taken_frequency,
  photos_taken_amount = EXCLUDED.photos_taken_amount,
  requested_client_info = EXCLUDED.requested_client_info;

-- Guide 3: Bennie DM
INSERT INTO public.guides_temp (
  id, name, cities, languages, tour_types, preferences, availability, tours_done, 
  content, phonenumber, google_calendar_id, Email, is_favourite, profile_picture, 
  birthday, photos_taken_frequency, photos_taken_amount, requested_client_info
) VALUES (
  3,
  'Bennie DM',
  ARRAY['Gent']::text[],
  ARRAY['Nederlands', 'Engels']::text[],
  ARRAY[]::text[],
  '{}'::jsonb,
  'No calendar connected',
  6,
  'Geboortedatum: 19 oktober 1984, Gent',
  '+32473346935',
  NULL,
  'nomulpe@gmail.com',
  NULL,
  NULL,
  NULL,
  1,
  7,
  0
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cities = EXCLUDED.cities,
  languages = EXCLUDED.languages,
  tour_types = EXCLUDED.tour_types,
  preferences = EXCLUDED.preferences,
  availability = EXCLUDED.availability,
  tours_done = EXCLUDED.tours_done,
  content = EXCLUDED.content,
  phonenumber = EXCLUDED.phonenumber,
  google_calendar_id = EXCLUDED.google_calendar_id,
  Email = EXCLUDED.Email,
  is_favourite = EXCLUDED.is_favourite,
  profile_picture = EXCLUDED.profile_picture,
  birthday = EXCLUDED.birthday,
  photos_taken_frequency = EXCLUDED.photos_taken_frequency,
  photos_taken_amount = EXCLUDED.photos_taken_amount,
  requested_client_info = EXCLUDED.requested_client_info;

-- Guide 4: Mizuho Ikeda
INSERT INTO public.guides_temp (
  id, name, cities, languages, tour_types, preferences, availability, tours_done, 
  content, phonenumber, google_calendar_id, Email, is_favourite, profile_picture, 
  birthday, photos_taken_frequency, photos_taken_amount, requested_client_info
) VALUES (
  4,
  'Mizuho Ikeda',
  ARRAY['Antwerpen', 'Brussel', 'Brugge', 'Gent']::text[],
  ARRAY['Japans']::text[],
  ARRAY[]::text[],
  '{"remarks": "Vergeet vaak foto te nemen (2023)"}'::jsonb,
  'No calendar connected',
  1,
  NULL,
  '+32473346935',
  NULL,
  'nomulpe@gmail.com',
  NULL,
  NULL,
  NULL,
  2,
  2,
  2
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cities = EXCLUDED.cities,
  languages = EXCLUDED.languages,
  tour_types = EXCLUDED.tour_types,
  preferences = EXCLUDED.preferences,
  availability = EXCLUDED.availability,
  tours_done = EXCLUDED.tours_done,
  content = EXCLUDED.content,
  phonenumber = EXCLUDED.phonenumber,
  google_calendar_id = EXCLUDED.google_calendar_id,
  Email = EXCLUDED.Email,
  is_favourite = EXCLUDED.is_favourite,
  profile_picture = EXCLUDED.profile_picture,
  birthday = EXCLUDED.birthday,
  photos_taken_frequency = EXCLUDED.photos_taken_frequency,
  photos_taken_amount = EXCLUDED.photos_taken_amount,
  requested_client_info = EXCLUDED.requested_client_info;

-- Guide 5: Christine Demeunynck
INSERT INTO public.guides_temp (
  id, name, cities, languages, tour_types, preferences, availability, tours_done, 
  content, phonenumber, google_calendar_id, Email, is_favourite, profile_picture, 
  birthday, photos_taken_frequency, photos_taken_amount, requested_client_info
) VALUES (
  5,
  'Christine Demeunynck',
  ARRAY['Gent']::text[],
  ARRAY['Nederlands', 'Engels', 'Frans', 'Spaans']::text[],
  ARRAY[]::text[],
  '{}'::jsonb,
  'No calendar connected',
  0,
  'Adres: Casinoplein 42, 9000 Gent. Gids in Gentse musea (Gravensteen, MSK, SMAK, STAM, etc.)',
  '+32473346935',
  NULL,
  'nomulpe@gmail.com',
  NULL,
  NULL,
  NULL,
  3,
  8,
  0
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cities = EXCLUDED.cities,
  languages = EXCLUDED.languages,
  tour_types = EXCLUDED.tour_types,
  preferences = EXCLUDED.preferences,
  availability = EXCLUDED.availability,
  tours_done = EXCLUDED.tours_done,
  content = EXCLUDED.content,
  phonenumber = EXCLUDED.phonenumber,
  google_calendar_id = EXCLUDED.google_calendar_id,
  Email = EXCLUDED.Email,
  is_favourite = EXCLUDED.is_favourite,
  profile_picture = EXCLUDED.profile_picture,
  birthday = EXCLUDED.birthday,
  photos_taken_frequency = EXCLUDED.photos_taken_frequency,
  photos_taken_amount = EXCLUDED.photos_taken_amount,
  requested_client_info = EXCLUDED.requested_client_info;

-- Guide 6: Veerle Manhaeve
INSERT INTO public.guides_temp (
  id, name, cities, languages, tour_types, preferences, availability, tours_done, 
  content, phonenumber, google_calendar_id, Email, is_favourite, profile_picture, 
  birthday, photos_taken_frequency, photos_taken_amount, requested_client_info
) VALUES (
  6,
  'Veerle Manhaeve',
  ARRAY['Gent']::text[],
  ARRAY['Nederlands', 'Engels', 'Frans']::text[],
  ARRAY[]::text[],
  '{}'::jsonb,
  'No calendar connected',
  4,
  'Begindatum: 16 mei 2022',
  '+32473346935',
  NULL,
  'nomulpe@gmail.com',
  NULL,
  NULL,
  NULL,
  3,
  5,
  1
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cities = EXCLUDED.cities,
  languages = EXCLUDED.languages,
  tour_types = EXCLUDED.tour_types,
  preferences = EXCLUDED.preferences,
  availability = EXCLUDED.availability,
  tours_done = EXCLUDED.tours_done,
  content = EXCLUDED.content,
  phonenumber = EXCLUDED.phonenumber,
  google_calendar_id = EXCLUDED.google_calendar_id,
  Email = EXCLUDED.Email,
  is_favourite = EXCLUDED.is_favourite,
  profile_picture = EXCLUDED.profile_picture,
  birthday = EXCLUDED.birthday,
  photos_taken_frequency = EXCLUDED.photos_taken_frequency,
  photos_taken_amount = EXCLUDED.photos_taken_amount,
  requested_client_info = EXCLUDED.requested_client_info;

-- Guide 7: Christien Batslé
INSERT INTO public.guides_temp (
  id, name, cities, languages, tour_types, preferences, availability, tours_done, 
  content, phonenumber, google_calendar_id, Email, is_favourite, profile_picture, 
  birthday, photos_taken_frequency, photos_taken_amount, requested_client_info
) VALUES (
  7,
  'Christien Batslé',
  ARRAY['Gent']::text[],
  ARRAY['Nederlands', 'Engels']::text[],
  ARRAY[]::text[],
  '{}'::jsonb,
  'No calendar connected',
  10,
  'Adres: Doornseelsestraat 86, 9940 Evergem. Begindatum: 25 oktober 2024',
  '+32473346935',
  NULL,
  'nomulpe@gmail.com',
  NULL,
  NULL,
  NULL,
  1,
  23,
  1
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cities = EXCLUDED.cities,
  languages = EXCLUDED.languages,
  tour_types = EXCLUDED.tour_types,
  preferences = EXCLUDED.preferences,
  availability = EXCLUDED.availability,
  tours_done = EXCLUDED.tours_done,
  content = EXCLUDED.content,
  phonenumber = EXCLUDED.phonenumber,
  google_calendar_id = EXCLUDED.google_calendar_id,
  Email = EXCLUDED.Email,
  is_favourite = EXCLUDED.is_favourite,
  profile_picture = EXCLUDED.profile_picture,
  birthday = EXCLUDED.birthday,
  photos_taken_frequency = EXCLUDED.photos_taken_frequency,
  photos_taken_amount = EXCLUDED.photos_taken_amount,
  requested_client_info = EXCLUDED.requested_client_info;

-- Guide 8: Lydia Janssens
INSERT INTO public.guides_temp (
  id, name, cities, languages, tour_types, preferences, availability, tours_done, 
  content, phonenumber, google_calendar_id, Email, is_favourite, profile_picture, 
  birthday, photos_taken_frequency, photos_taken_amount, requested_client_info
) VALUES (
  8,
  'Lydia Janssens',
  ARRAY['Antwerpen']::text[],
  ARRAY['Nederlands', 'Engels', 'Frans']::text[],
  ARRAY[]::text[],
  '{"remarks": "Vergeet vaak foto te nemen (2023)"}'::jsonb,
  'No calendar connected',
  2,
  'Geboortedatum: 10 april 1952',
  '+32473346935',
  NULL,
  'nomulpe@gmail.com',
  NULL,
  NULL,
  NULL,
  1,
  3,
  2
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cities = EXCLUDED.cities,
  languages = EXCLUDED.languages,
  tour_types = EXCLUDED.tour_types,
  preferences = EXCLUDED.preferences,
  availability = EXCLUDED.availability,
  tours_done = EXCLUDED.tours_done,
  content = EXCLUDED.content,
  phonenumber = EXCLUDED.phonenumber,
  google_calendar_id = EXCLUDED.google_calendar_id,
  Email = EXCLUDED.Email,
  is_favourite = EXCLUDED.is_favourite,
  profile_picture = EXCLUDED.profile_picture,
  birthday = EXCLUDED.birthday,
  photos_taken_frequency = EXCLUDED.photos_taken_frequency,
  photos_taken_amount = EXCLUDED.photos_taken_amount,
  requested_client_info = EXCLUDED.requested_client_info;

-- Guide 9: Katrijn Krekels
INSERT INTO public.guides_temp (
  id, name, cities, languages, tour_types, preferences, availability, tours_done, 
  content, phonenumber, google_calendar_id, Email, is_favourite, profile_picture, 
  birthday, photos_taken_frequency, photos_taken_amount, requested_client_info
) VALUES (
  9,
  'Katrijn Krekels',
  ARRAY['Antwerpen']::text[],
  ARRAY['Nederlands', 'Engels', 'Frans']::text[],
  ARRAY[]::text[],
  '{"remarks": "Vergeet vaak foto te nemen (2023)"}'::jsonb,
  'No calendar connected',
  3,
  NULL,
  '+32473346935',
  NULL,
  'nomulpe@gmail.com',
  NULL,
  NULL,
  NULL,
  0,
  0,
  0
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cities = EXCLUDED.cities,
  languages = EXCLUDED.languages,
  tour_types = EXCLUDED.tour_types,
  preferences = EXCLUDED.preferences,
  availability = EXCLUDED.availability,
  tours_done = EXCLUDED.tours_done,
  content = EXCLUDED.content,
  phonenumber = EXCLUDED.phonenumber,
  google_calendar_id = EXCLUDED.google_calendar_id,
  Email = EXCLUDED.Email,
  is_favourite = EXCLUDED.is_favourite,
  profile_picture = EXCLUDED.profile_picture,
  birthday = EXCLUDED.birthday,
  photos_taken_frequency = EXCLUDED.photos_taken_frequency,
  photos_taken_amount = EXCLUDED.photos_taken_amount,
  requested_client_info = EXCLUDED.requested_client_info;

-- Guide 10: Patrik Mertens
INSERT INTO public.guides_temp (
  id, name, cities, languages, tour_types, preferences, availability, tours_done, 
  content, phonenumber, google_calendar_id, Email, is_favourite, profile_picture, 
  birthday, photos_taken_frequency, photos_taken_amount, requested_client_info
) VALUES (
  10,
  'Patrik Mertens',
  ARRAY['Antwerpen']::text[],
  ARRAY['Nederlands', 'Engels', 'Frans']::text[],
  ARRAY[]::text[],
  '{"remarks": "Vergeet vaak foto te nemen (2023)"}'::jsonb,
  'No calendar connected',
  0,
  'Adres: 2000 Antwerpen. Begindatum: 17 september 2022',
  '+32473346935',
  NULL,
  'nomulpe@gmail.com',
  NULL,
  NULL,
  NULL,
  2,
  6,
  0
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cities = EXCLUDED.cities,
  languages = EXCLUDED.languages,
  tour_types = EXCLUDED.tour_types,
  preferences = EXCLUDED.preferences,
  availability = EXCLUDED.availability,
  tours_done = EXCLUDED.tours_done,
  content = EXCLUDED.content,
  phonenumber = EXCLUDED.phonenumber,
  google_calendar_id = EXCLUDED.google_calendar_id,
  Email = EXCLUDED.Email,
  is_favourite = EXCLUDED.is_favourite,
  profile_picture = EXCLUDED.profile_picture,
  birthday = EXCLUDED.birthday,
  photos_taken_frequency = EXCLUDED.photos_taken_frequency,
  photos_taken_amount = EXCLUDED.photos_taken_amount,
  requested_client_info = EXCLUDED.requested_client_info;

-- Guide 11: Jacky Andrzejewski
INSERT INTO public.guides_temp (
  id, name, cities, languages, tour_types, preferences, availability, tours_done, 
  content, phonenumber, google_calendar_id, Email, is_favourite, profile_picture, 
  birthday, photos_taken_frequency, photos_taken_amount, requested_client_info
) VALUES (
  11,
  'Jacky Andrzejewski',
  ARRAY['Antwerpen']::text[],
  ARRAY['Nederlands', 'Frans', 'Engels', 'Duits']::text[],
  ARRAY[]::text[],
  '{"remarks": ["Vergeet vaak foto te nemen (2023)", "Vergeet bonnetjes toe te voegen (2023)"]}'::jsonb,
  'No calendar connected',
  5,
  'Adres: Pieter Breugellaan 2A, 2840 Rumst. Begindatum: 24 september 2016',
  '+32473346935',
  NULL,
  'nomulpe@gmail.com',
  NULL,
  NULL,
  NULL,
  4,
  33,
  1
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cities = EXCLUDED.cities,
  languages = EXCLUDED.languages,
  tour_types = EXCLUDED.tour_types,
  preferences = EXCLUDED.preferences,
  availability = EXCLUDED.availability,
  tours_done = EXCLUDED.tours_done,
  content = EXCLUDED.content,
  phonenumber = EXCLUDED.phonenumber,
  google_calendar_id = EXCLUDED.google_calendar_id,
  Email = EXCLUDED.Email,
  is_favourite = EXCLUDED.is_favourite,
  profile_picture = EXCLUDED.profile_picture,
  birthday = EXCLUDED.birthday,
  photos_taken_frequency = EXCLUDED.photos_taken_frequency,
  photos_taken_amount = EXCLUDED.photos_taken_amount,
  requested_client_info = EXCLUDED.requested_client_info;

-- Guide 12: Nicole Loncke
INSERT INTO public.guides_temp (
  id, name, cities, languages, tour_types, preferences, availability, tours_done, 
  content, phonenumber, google_calendar_id, Email, is_favourite, profile_picture, 
  birthday, photos_taken_frequency, photos_taken_amount, requested_client_info
) VALUES (
  12,
  'Nicole Loncke',
  ARRAY['Brugge']::text[],
  ARRAY['Nederlands', 'Engels', 'Frans']::text[],
  ARRAY[]::text[],
  '{}'::jsonb,
  'No calendar connected',
  4,
  'Adres: Kooidreef 16, 8200 Brugge. Begindatum: 31 mei 2024',
  '+32473346935',
  NULL,
  'nomulpe@gmail.com',
  NULL,
  NULL,
  NULL,
  6,
  12,
  0
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cities = EXCLUDED.cities,
  languages = EXCLUDED.languages,
  tour_types = EXCLUDED.tour_types,
  preferences = EXCLUDED.preferences,
  availability = EXCLUDED.availability,
  tours_done = EXCLUDED.tours_done,
  content = EXCLUDED.content,
  phonenumber = EXCLUDED.phonenumber,
  google_calendar_id = EXCLUDED.google_calendar_id,
  Email = EXCLUDED.Email,
  is_favourite = EXCLUDED.is_favourite,
  profile_picture = EXCLUDED.profile_picture,
  birthday = EXCLUDED.birthday,
  photos_taken_frequency = EXCLUDED.photos_taken_frequency,
  photos_taken_amount = EXCLUDED.photos_taken_amount,
  requested_client_info = EXCLUDED.requested_client_info;

-- Guide 13: Xavier Graff
INSERT INTO public.guides_temp (
  id, name, cities, languages, tour_types, preferences, availability, tours_done, 
  content, phonenumber, google_calendar_id, Email, is_favourite, profile_picture, 
  birthday, photos_taken_frequency, photos_taken_amount, requested_client_info
) VALUES (
  13,
  'Xavier Graff',
  ARRAY['Antwerpen']::text[],
  ARRAY['Nederlands', 'Engels', 'Frans']::text[],
  ARRAY[]::text[],
  '{}'::jsonb,
  'No calendar connected',
  2,
  'Adres: Parklaan 67, 2610 Wilrijk. BTW: BE0633451273. IBAN: BE76737066702495. Begindatum: 17 februari 2023',
  '+32473346935',
  NULL,
  'nomulpe@gmail.com',
  NULL,
  NULL,
  NULL,
  1,
  3,
  3
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cities = EXCLUDED.cities,
  languages = EXCLUDED.languages,
  tour_types = EXCLUDED.tour_types,
  preferences = EXCLUDED.preferences,
  availability = EXCLUDED.availability,
  tours_done = EXCLUDED.tours_done,
  content = EXCLUDED.content,
  phonenumber = EXCLUDED.phonenumber,
  google_calendar_id = EXCLUDED.google_calendar_id,
  Email = EXCLUDED.Email,
  is_favourite = EXCLUDED.is_favourite,
  profile_picture = EXCLUDED.profile_picture,
  birthday = EXCLUDED.birthday,
  photos_taken_frequency = EXCLUDED.photos_taken_frequency,
  photos_taken_amount = EXCLUDED.photos_taken_amount,
  requested_client_info = EXCLUDED.requested_client_info;

-- Guide 14: Tom Willemse
INSERT INTO public.guides_temp (
  id, name, cities, languages, tour_types, preferences, availability, tours_done, 
  content, phonenumber, google_calendar_id, Email, is_favourite, profile_picture, 
  birthday, photos_taken_frequency, photos_taken_amount, requested_client_info
) VALUES (
  14,
  'Tom Willemse',
  ARRAY['Antwerpen']::text[],
  ARRAY['Nederlands', 'Engels', 'Frans']::text[],
  ARRAY[]::text[],
  '{}'::jsonb,
  'No calendar connected',
  9,
  'Adres: Van Schoonbekestraat 123/17, 2018 Antwerpen. Begindatum: 3 november 2023',
  '+32473346935',
  NULL,
  'nomulpe@gmail.com',
  NULL,
  NULL,
  NULL,
  1,
  1,
  0
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  cities = EXCLUDED.cities,
  languages = EXCLUDED.languages,
  tour_types = EXCLUDED.tour_types,
  preferences = EXCLUDED.preferences,
  availability = EXCLUDED.availability,
  tours_done = EXCLUDED.tours_done,
  content = EXCLUDED.content,
  phonenumber = EXCLUDED.phonenumber,
  google_calendar_id = EXCLUDED.google_calendar_id,
  Email = EXCLUDED.Email,
  is_favourite = EXCLUDED.is_favourite,
  profile_picture = EXCLUDED.profile_picture,
  birthday = EXCLUDED.birthday,
  photos_taken_frequency = EXCLUDED.photos_taken_frequency,
  photos_taken_amount = EXCLUDED.photos_taken_amount,
  requested_client_info = EXCLUDED.requested_client_info;

